### ISSUE TITLE
RANSAC algorithm for point cloud data 

### ISSUE THREAD

**Issue by speak2sainow** [PhiLhoSoft/Processing#1]
Hi thanks for the examples of RANSAC algorithm..!

I have the data of point cloud from the Kinect in .png file format..   Now looking for how to apply your fitting planes algorithim.. 

Any kind of help will be greatly appreciated.

Thanks,
Sai

**Comment by PhiLhoSoft** [comment]
Thanks for your interest.
I fear I won't have time to help you, alas.
Even less as I don't do much Processing lately.
I suggest to get help of the Processing forum, if not already done. There are competent and helpful people there.
Regards.
